### ISSUE TITLE
Bioconductor GCE deployment not working

### ISSUE THREAD

**Issue by awblocker** [googlegenomics/readthedocs#137]
The Bioconductor deployment workflow linked from http://googlegenomics.readthedocs.io/en/latest/use_cases/run_familiar_tools/bioconductor.html is no longer working. It appears not to be present in Cloud Launcher.

**Comment by pgrosu** [comment]
Hi Alex,

If you click on the [Go To The Images Page] under the [Public Images section](https://cloud.google.com/compute/docs/images) at the [following location](https://cloud.google.com/compute/docs/images), do you see anything with something like Bioconductor in the VM name?

https://cloud.google.com/compute/docs/images

Thanks,
Paul

**Comment by awblocker** [comment]
Nope, not seeing anything related to Bioconductor there.

**Comment by pgrosu** [comment]
Interestingly, I think it is part of the [Google Cloud Launcher](https://console.cloud.google.com/launcher), and when I specify the name like this:

https://console.cloud.google.com/launcher/details/click-to-deploy-images/bioconductor

I then get the following permission error:

![launcher_error](https://cloud.githubusercontent.com/assets/6555937/16360876/4c540086-3b47-11e6-8cb6-224df0481f74.png)

Since you're part of Google you would have more permissions than I would, so try to see if you have access to that page and launch it, by clicking on the link above.

Let me know if that worked for you.

Thanks,
~p

**Comment by awblocker** [comment]
Sadly, my magic appears ineffective. Same thing on Google and personal accounts. @deflaux for any thoughts she has on this.

**Comment by pgrosu** [comment]
Hi Alex,

I'm discovering more and more - it's like a riddle wrapped up in an enigma :)  I think what we are experiencing might be because we could have a `v1beta2`-based Deployment, which might have been deprecated (and possibly removed if it was created before the `v2`-migration) based on the following website, as it is now at `v2` of the API:

https://cloud.google.com/deployment-manager/deployment-manager-and-click-to-deploy#prerequisites-for-this-guide

As a double-check on the status of the Bioconductor Deployment, it might not be a bad idea to try the following instructions as well from that webpage - though it might be tied to the account that created it:

> Determine if your deployment is affected
>
> 1. Visit the Deployments page in the Cloud Platform Console.
>
> 2. Click the deployment you want to check. A side panel will open displaying information about the deployment.
>
> 3. Next to the field labeled Deployed by, check the field value. If the field value is Deployment Manager (v1beta2), then the deployment is using an older API and will be removed from the list of deployments on March 1st, 2016. If the field says Deployment Manager (without the v1beta2 specification), then the deployment is using the current API version and won't be affected by the deprecation of v1beta2.
>
> ![clicktodeploycheck](https://cloud.githubusercontent.com/assets/6555937/16368266/602d62ec-3bfa-11e6-878a-3f4630d0e830.png)

In any case, I think most likely the click-to-deploy for the Bioconductor image would need to be updated as a `v2` Deployment.

~p

**Comment by deflaux** [comment]
Agreed - its broken.  We'll get it fixed, thanks!

**Comment by deflaux** [comment]
Its fixed now!
